services:
  - type: web
    name: alx-travel-app
    env: python
    plan: free
    buildCommand: >
      pip install -r requirements.txt &&
      python alx_travel_app/manage.py migrate &&
      python create_superuser.py &&
      python alx_travel_app/manage.py collectstatic --noinput
    startCommand: gunicorn alx_travel_app.wsgi:application
    envVars:
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*"
      - key: DATABASE_URL
        fromDatabase:
          name: alx-travel-db
          property: connectionString
    healthCheckPath: /
databases:
  - name: alx-travel-db
    databaseName: alx_travel_app
    user: alx_user
    plan: free
